// <auto-generated />
using System;
using System.Collections.Generic;
using CineQuizAI.Domain.ValueObjects;
using CineQuizAI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CineQuizAI.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110205102_RemoveHintFeature")]
    partial class RemoveHintFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CineQuizAI.Domain.Entities.BlockedTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("TitleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("title_type");

                    b.Property<long>("TmdbId")
                        .HasColumnType("bigint")
                        .HasColumnName("tmdb_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TmdbId", "TitleType")
                        .IsUnique();

                    b.ToTable("blocked_title", (string)null);
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddresseeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("addressee_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeUserId");

                    b.HasIndex("RequesterUserId");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_friendship_status_updated");

                    b.ToTable("friendship", (string)null);
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.PrivateLeaderboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invite_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.ToTable("private_leaderboard", (string)null);
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.PrivateLeaderboardMember", b =>
                {
                    b.Property<Guid>("LeaderboardId")
                        .HasColumnType("uuid")
                        .HasColumnName("leaderboard_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("LeaderboardId", "UserId");

                    b.HasIndex("LeaderboardId")
                        .HasDatabaseName("ix_private_leaderboard_member_leaderboard");

                    b.HasIndex("UserId");

                    b.ToTable("private_leaderboard_member", (string)null);
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.QuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("SelectedIndex")
                        .HasColumnType("integer")
                        .HasColumnName("selected_index");

                    b.Property<int>("TimeSpentMs")
                        .HasColumnType("integer")
                        .HasColumnName("time_spent_ms");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("question_answer", (string)null);
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.QuestionReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ReporterUserId");

                    b.ToTable("question_report", (string)null);
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.QuestionSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<string>("FactsHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("facts_hash");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<int>("PromptVersion")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_version");

                    b.Property<string>("TitleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("title_type");

                    b.Property<long>("TmdbId")
                        .HasColumnType("bigint")
                        .HasColumnName("tmdb_id");

                    b.Property<int>("UsesCount")
                        .HasColumnType("integer")
                        .HasColumnName("uses_count");

                    b.HasKey("Id");

                    b.HasIndex("TmdbId", "TitleType", "Difficulty", "LanguageCode", "IsActive")
                        .HasDatabaseName("ix_question_set_lookup");

                    b.ToTable("question_set", (string)null);
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.QuestionSetQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("integer")
                        .HasColumnName("correct_index");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<List<string>>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_reference");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("SetId", "Ordinal")
                        .HasDatabaseName("ix_question_set_question_ordinal");

                    b.ToTable("question_set_question", (string)null);
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("integer")
                        .HasColumnName("correct_index");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<List<string>>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_reference");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Ordinal")
                        .HasDatabaseName("ix_quiz_question_session_ordinal");

                    b.ToTable("quiz_question", (string)null);
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.QuizSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer")
                        .HasColumnName("question_count");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("TitleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("title_type");

                    b.Property<long>("TmdbId")
                        .HasColumnType("bigint")
                        .HasColumnName("tmdb_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("FinishedAt")
                        .HasDatabaseName("ix_quiz_session_finished_at");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("UserId", "FinishedAt")
                        .HasDatabaseName("ix_quiz_session_user_finished");

                    b.ToTable("quiz_session", (string)null);
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.TitleFactsSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Collection>("BelongsToCollection")
                        .HasColumnType("jsonb")
                        .HasColumnName("belongs_to_collection");

                    b.Property<List<CastMember>>("CastTop")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cast_top");

                    b.Property<List<string>>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<List<string>>("Genres")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("genres");

                    b.Property<List<string>>("Keywords")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("keywords");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<List<string>>("OriginCountry")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("origin_country");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("original_language");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("overview");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("poster_url");

                    b.Property<List<string>>("ProductionCompanies")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("production_companies");

                    b.Property<int?>("SeasonsCount")
                        .HasColumnType("integer")
                        .HasColumnName("seasons_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("TitleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("title_type");

                    b.Property<long>("TmdbId")
                        .HasColumnType("bigint")
                        .HasColumnName("tmdb_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("TmdbId", "TitleType", "LanguageCode")
                        .IsUnique();

                    b.ToTable("title_facts_snapshot", (string)null);
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_category");

                    b.Property<string>("DefaultDifficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_difficulty");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("user_preference", (string)null);
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.UserQuestionSetPlay", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at");

                    b.HasKey("UserId", "SetId");

                    b.HasIndex("SetId");

                    b.ToTable("user_question_set_play", (string)null);
                });

            modelBuilder.Entity("CineQuizAI.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.BlockedTitle", b =>
                {
                    b.HasOne("CineQuizAI.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.Friendship", b =>
                {
                    b.HasOne("CineQuizAI.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AddresseeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineQuizAI.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.PrivateLeaderboard", b =>
                {
                    b.HasOne("CineQuizAI.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.PrivateLeaderboardMember", b =>
                {
                    b.HasOne("CineQuizAI.Domain.Entities.PrivateLeaderboard", "Leaderboard")
                        .WithMany("Members")
                        .HasForeignKey("LeaderboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineQuizAI.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leaderboard");
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.QuestionAnswer", b =>
                {
                    b.HasOne("CineQuizAI.Domain.Entities.QuizQuestion", "Question")
                        .WithOne("Answer")
                        .HasForeignKey("CineQuizAI.Domain.Entities.QuestionAnswer", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.QuestionReport", b =>
                {
                    b.HasOne("CineQuizAI.Domain.Entities.QuizQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineQuizAI.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.QuestionSetQuestion", b =>
                {
                    b.HasOne("CineQuizAI.Domain.Entities.QuestionSet", "Set")
                        .WithMany("Questions")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.QuizQuestion", b =>
                {
                    b.HasOne("CineQuizAI.Domain.Entities.QuizSession", "Session")
                        .WithMany("Questions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.QuizSession", b =>
                {
                    b.HasOne("CineQuizAI.Domain.Entities.TitleFactsSnapshot", "Snapshot")
                        .WithMany("QuizSessions")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CineQuizAI.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.UserPreference", b =>
                {
                    b.HasOne("CineQuizAI.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.UserQuestionSetPlay", b =>
                {
                    b.HasOne("CineQuizAI.Domain.Entities.QuestionSet", "Set")
                        .WithMany("Plays")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineQuizAI.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CineQuizAI.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CineQuizAI.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineQuizAI.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CineQuizAI.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.PrivateLeaderboard", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.QuestionSet", b =>
                {
                    b.Navigation("Plays");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.QuizQuestion", b =>
                {
                    b.Navigation("Answer");
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.QuizSession", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CineQuizAI.Domain.Entities.TitleFactsSnapshot", b =>
                {
                    b.Navigation("QuizSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
